name: Releases CD

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Set up Hub
      run: |
        sudo snap install hub --classic

    - name: Inject Version
      run: |
        sed -i "1s/.*/$(git describe --tags --abbrev=0)/" ./CHANGELOG.md
        sed -i -E "s/(mod_version=)debug/\1$(git describe --tags --abbrev=0)/" gradle.properties
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew jar

    - name: Deploy to Releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: 'hub release create 
              -a build/libs/*.jar
              -F ./CHANGELOG.md
              $(git describe --tags --abbrev=0)'

    - name: Deploy to Curseforge
      uses: itsmeow/curseforge-upload@master
      with:
        token: ${{ secrets.CURSEFORGE_APIKEY }}
        project_id: 340295
        game_endpoint: minecraft
        file_path: build/libs/*.jar
        changelog: Test changelog message!
        display_name: $(git describe --tags --abbrev=0)
        game_versions: minecraft-1-12:1.12.2,4458,2:Java 7,Minecraft 1.12:1-12,1.12.1,Forge
        release_type: release
